# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: UIBOT

on:
  
  push:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: wget google-chrome-stable
      # You may pin to the exact commit or the version.
      # uses: wei/wget@ca0a6b7f0fdd7ffbe9d4cec0b9696f2dc658d3c9
      uses: wei/wget@v1.1.1
      with:
        args: -qO- https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  
    - name: wget TagUI_Linux
      # You may pin to the exact commit or the version.
      # uses: wei/wget@ca0a6b7f0fdd7ffbe9d4cec0b9696f2dc658d3c9
      uses: wei/wget@v1.1.1
      with:
        args: -qO- https://github.com/kelaberetiv/TagUI/releases/download/v6.14.0/TagUI_Linux.zip

    - name: Set up tagui v6.14
      # You may pin to the exact commit or the version.
      # uses: montudor/action-zip@c25e01d7489d0274569440a2f0281b4569df16bc
      uses: montudor/action-zip@v0.1.1
      with:
        # See montudor/action-zip README.md for more info
        args: unzip -qq TagUI_Linux.zip
       
    - name: Set up google-chrome-stable_current
      run:  sudo apt install ./google-chrome-stable_current_amd64.deb

    - name: Startup UIBot
      run: tagui/tagui demo.tag
      env:
        GITHUB_TOKEN: ${{ github.token }}
